GET http://127.0.0.1:8000/products/ HTTP/1.1
###

GET http://127.0.0.1:8000/product/6/ HTTP/1.1
###

PUT http://127.0.0.1:8000/product/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzM2ODg2LCJpYXQiOjE3NTE3MzY1ODYsImp0aSI6IjhjZWUzNTBlMTNiMTQ3YWRiMDVhZDNjZjA1ZDY1YTY1IiwidXNlcl9pZCI6MX0.Uf1Fle_bqGMSZCgnTUxrIu91tAYXUMGkMrNuhR64AVM

{
  "name": "A very Newly made Product",
  "price": 29.99,
  "stock": 10,
  "description": "A brand very new product (futuristic)"
}
###

DELETE http://127.0.0.1:8000/product/5/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzM2ODg2LCJpYXQiOjE3NTE3MzY1ODYsImp0aSI6IjhjZWUzNTBlMTNiMTQ3YWRiMDVhZDNjZjA1ZDY1YTY1IiwidXNlcl9pZCI6MX0.Uf1Fle_bqGMSZCgnTUxrIu91tAYXUMGkMrNuhR64AVM
###


POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzMyOTUwLCJpYXQiOjE3NTE3MzI2NTAsImp0aSI6IjNlMDI0Mjk1MDJhYzQxODg4YTdlZThiYjBkZWExY2NmIiwidXNlcl9pZCI6Mn0.rFdLBiNA8xfIjLYxRX5YUBJ3jIu2O4eA7qPpWaB8xCo

{
  "name": "A very New Product",
  "price": 29.99,
  "stock": 10,
  "description": "A brand very new product"
}
###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}
###


POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MTgyMTIzNiwiaWF0IjoxNzUxNzM0ODM2LCJqdGkiOiIzOWZlZDRjODA5OTM0MTM0YmNkNTliYTA5YWZlMGI2MiIsInVzZXJfaWQiOjF9.TqSzszofTn9zPRFHQsh_aTRma6_kmNPOYeJrj0WKP88"
}
###


GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxOTg2MDMzLCJpYXQiOjE3NTE5ODU3MzMsImp0aSI6IjgzMzNiNDY4Y2JjZjQxZWVhMTA2Nzc1OTRjNWZiMDk0IiwidXNlcl9pZCI6Mn0.cjjQo6ZA7NzlbR36zn7RiWhRlkGjlHDdfPiCJCTALis
###

GET http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxOTg2MjU0LCJpYXQiOjE3NTE5ODU5NTQsImp0aSI6Ijc1NTdhNTQ4ODFmZjQxNTZiZTE5NjI1ODUzOWJhYWQ0IiwidXNlcl9pZCI6Mn0.KgTFjbdXqFpKFueWje_exDJmU6cY1dUSL7EAWpVEdhU
###

GET http://127.0.0.1:8000/orders/b88f4d3d-76f6-46d5-8a62-615132383bf1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxOTg2NjI2LCJpYXQiOjE3NTE5ODYzMjYsImp0aSI6IjQ4ZTg4ODJmYjgxYjQ3ZTg4MzhjMDQ5YzQyYWYxMjQxIiwidXNlcl9pZCI6MX0.xBoONyyTSQE-X1eCT3_wTAKg_DYistcn-ej4idQQn-4

###
POST http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxOTg2MjU0LCJpYXQiOjE3NTE5ODU5NTQsImp0aSI6Ijc1NTdhNTQ4ODFmZjQxNTZiZTE5NjI1ODUzOWJhYWQ0IiwidXNlcl9pZCI6Mn0.KgTFjbdXqFpKFueWje_exDJmU6cY1dUSL7EAWpVEdhU

{
    "user": 2
}
###