GET http://127.0.0.1:8000/products/ HTTP/1.1
###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzMyOTUwLCJpYXQiOjE3NTE3MzI2NTAsImp0aSI6IjNlMDI0Mjk1MDJhYzQxODg4YTdlZThiYjBkZWExY2NmIiwidXNlcl9pZCI6Mn0.rFdLBiNA8xfIjLYxRX5YUBJ3jIu2O4eA7qPpWaB8xCo

{
  "name": "A very New Product",
  "price": 29.99,
  "stock": 10,
  "description": "A brand very new product"
}
###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "nzannin",
    "password": "nzannin"
}
###

GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzMzMzAyLCJpYXQiOjE3NTE3MzMwMDIsImp0aSI6ImIwM2E3YzI5NjFhZTRiZTE5YWZhODkyOWI1NDE1YTQyIiwidXNlcl9pZCI6Mn0.NB9h38Jbr4keGAEIRm1qrkuRVOPOvFKRclCobOITCJU

