GET http://127.0.0.1:8000/products/ HTTP/1.1
###

GET http://127.0.0.1:8000/product/6/ HTTP/1.1
###

PUT http://127.0.0.1:8000/product/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzM2ODg2LCJpYXQiOjE3NTE3MzY1ODYsImp0aSI6IjhjZWUzNTBlMTNiMTQ3YWRiMDVhZDNjZjA1ZDY1YTY1IiwidXNlcl9pZCI6MX0.Uf1Fle_bqGMSZCgnTUxrIu91tAYXUMGkMrNuhR64AVM

{
  "name": "A very Newly made Product",
  "price": 29.99,
  "stock": 10,
  "description": "A brand very new product (futuristic)"
}
###

DELETE http://127.0.0.1:8000/product/5/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzM2ODg2LCJpYXQiOjE3NTE3MzY1ODYsImp0aSI6IjhjZWUzNTBlMTNiMTQ3YWRiMDVhZDNjZjA1ZDY1YTY1IiwidXNlcl9pZCI6MX0.Uf1Fle_bqGMSZCgnTUxrIu91tAYXUMGkMrNuhR64AVM
###


POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzMyOTUwLCJpYXQiOjE3NTE3MzI2NTAsImp0aSI6IjNlMDI0Mjk1MDJhYzQxODg4YTdlZThiYjBkZWExY2NmIiwidXNlcl9pZCI6Mn0.rFdLBiNA8xfIjLYxRX5YUBJ3jIu2O4eA7qPpWaB8xCo

{
  "name": "A very New Product",
  "price": 29.99,
  "stock": 10,
  "description": "A brand very new product"
}
###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}
###


POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MTgyMTIzNiwiaWF0IjoxNzUxNzM0ODM2LCJqdGkiOiIzOWZlZDRjODA5OTM0MTM0YmNkNTliYTA5YWZlMGI2MiIsInVzZXJfaWQiOjF9.TqSzszofTn9zPRFHQsh_aTRma6_kmNPOYeJrj0WKP88"
}
###


GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxOTg2MDMzLCJpYXQiOjE3NTE5ODU3MzMsImp0aSI6IjgzMzNiNDY4Y2JjZjQxZWVhMTA2Nzc1OTRjNWZiMDk0IiwidXNlcl9pZCI6Mn0.cjjQo6ZA7NzlbR36zn7RiWhRlkGjlHDdfPiCJCTALis
###

GET http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNTY3OTYyLCJpYXQiOjE3NTI1NjQzNjIsImp0aSI6IjBhZDg2ZjY5YmJmNjRjMmQ4OWI1MGNjZTdkNGZkZmFhIiwidXNlcl9pZCI6MX0.G3VJY6vz91a-jNatqraU1ESSFhIwqcM4l6rLoDgxzec
###

GET http://127.0.0.1:8000/orders/a643ab40-c4d5-4a00-b60f-e7052a11cfc6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMzQxODQ4LCJpYXQiOjE3NTIzNDE1NDgsImp0aSI6ImE2ODBmZDViZDlkYTQ5M2M4YzI5MjM1ODI1NTQ2NjI0IiwidXNlcl9pZCI6MX0.6xW2NRca9PER1Z6R2ucEVhM13rlo8qke3HudarHdkWA

###
POST http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNTY4Mzk2LCJpYXQiOjE3NTI1NjQ3OTYsImp0aSI6IjZhZTBiNzE2YjQ0YTQ5OGY5NDJiN2I5YWIwYzBlYzMxIiwidXNlcl9pZCI6MX0._SCJJyPco6oFmPpoc8WAJIx7NYwVQHrkxNti9DnBqxU

{
    "status": "Pending",
    "items": [
        {
            "product": 6,
            "quantity": 2
        },
        {
            "product": 3,
            "quantity": 2
        }   
    ]
}
###

PUT http://127.0.0.1:8000/orders/a643ab40-c4d5-4a00-b60f-e7052a11cfc6/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMzQxODQ4LCJpYXQiOjE3NTIzNDE1NDgsImp0aSI6ImE2ODBmZDViZDlkYTQ5M2M4YzI5MjM1ODI1NTQ2NjI0IiwidXNlcl9pZCI6MX0.6xW2NRca9PER1Z6R2ucEVhM13rlo8qke3HudarHdkWA

{
    "status": "Confirmed",
    "items": [
        {
            "product": 6,
            "quantity": 1
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}

###

DELETE http://127.0.0.1:8000/orders/a643ab40-c4d5-4a00-b60f-e7052a11cfc6/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMzQyNTc1LCJpYXQiOjE3NTIzNDIyNzUsImp0aSI6IjA2ZWY3OWUwYWNkMDQ5ODRhNWE1YTI0MDIyZGM1MzQ5IiwidXNlcl9pZCI6MX0.UGxFmLUX2S8M-4hlitJcBkFNzytamTYK4Ko3ALElc4s
